development:
  adapter: postgresql
  encoding: unicode
  database: rails4test_development
  pool: 5
  username: rails4test

test:
  adapter: postgresql
  encoding: unicode
  database: rails4test_test
  pool: 5
  username: rails4test

production:
  adapter: postgresql
  encoding: unicode
  database: rails4test_production
  pool: 5
  username: rails4test
